#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'
module QLS
  class Parser < Racc::Parser


  require_relative '../ast/ast.rb'
  
  include AST


  def initialize(tokenizer)
    @tokenizer = tokenizer
    super()
  end

  def next_token
    @tokenizer.next_token
  end

  def parse
    do_parse
  end
##### State transition tables begin ###

racc_action_table = [
    50,    35,    49,    27,    50,    13,    49,    27,    50,    13,
    49,     5,    50,    22,    49,    45,    46,    47,    48,    45,
    46,    47,    48,    45,    46,    47,    48,    45,    46,    47,
    48,    50,    66,    49,    18,    19,    20,    30,    31,    32,
    33,    34,    60,    13,    21,    38,    45,    46,    47,    48,
    30,    31,    32,    33,    34,    14,    12,     5,     7,    13,
    30,    31,    32,    33,    34,    30,    31,    32,    33,    34,
    61,    55,    12,    60,    13,    13,     6,     5,     5,    64,
     3,     2 ]

racc_action_check = [
    33,    23,    33,    23,    30,    23,    30,    21,    31,    21,
    31,    27,    34,    17,    34,    33,    33,    33,    33,    30,
    30,    30,    30,    31,    31,    31,    31,    34,    34,    34,
    34,    32,    65,    32,    13,    13,    13,    65,    65,    65,
    65,    65,    55,    55,    16,    28,    32,    32,    32,    32,
    28,    28,    28,    28,    28,     8,     8,    12,     4,     8,
    22,    22,    22,    22,    22,    64,    64,    64,    64,    64,
    56,    37,     7,    56,    56,     7,     3,     2,    60,    63,
     1,     0 ]

racc_action_pointer = [
    76,    80,    74,    76,    52,   nil,   nil,    64,    48,   nil,
   nil,   nil,    54,    13,   nil,   nil,    38,     7,   nil,   nil,
   nil,    -2,    48,    -6,   nil,   nil,   nil,     8,    38,   nil,
     2,     6,    29,    -2,    10,   nil,   nil,    65,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    32,    63,   nil,   nil,   nil,
    75,   nil,   nil,    73,    53,    25,   nil ]

racc_action_default = [
   -39,   -39,   -39,   -39,   -39,   -33,    67,   -39,   -39,    -3,
    -4,    -5,   -39,   -39,    -1,    -2,   -39,   -39,   -34,   -35,
   -36,   -39,   -39,   -39,    -8,    -9,   -10,   -39,   -39,   -19,
   -39,   -39,   -39,   -39,   -39,    -6,    -7,   -39,   -17,   -18,
   -20,   -25,   -26,   -27,   -28,   -29,   -30,   -31,   -32,   -37,
   -38,   -21,   -22,   -23,   -24,   -39,   -39,   -13,   -14,   -15,
   -39,   -11,   -12,   -39,   -39,   -39,   -16 ]

racc_goto_table = [
     4,    28,    39,    25,    24,    25,    36,     9,    15,    23,
    16,    40,    51,    52,    53,    54,    57,    62,    56,    17,
     8,     1,   nil,   nil,   nil,    37,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    58,    58,    39,
   nil,   nil,   nil,    65,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    63 ]

racc_goto_check = [
     2,    13,    15,     5,     8,     5,     8,     4,     4,     7,
     2,    16,    16,    16,    16,    16,    11,    11,    10,    14,
     3,     1,   nil,   nil,   nil,     2,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,     5,    15,
   nil,   nil,   nil,    13,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,    21,    -2,    13,     0,   -18,   nil,   -12,   -17,   nil,
   -37,   -39,   nil,   -21,     6,   -26,   -19,   nil,   nil,   nil,
   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,    10,    11,   nil,   nil,    26,
   nil,   nil,    59,   nil,   nil,    29,   nil,    41,    42,    43,
    44 ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 25, :_reduce_1,
  2, 27, :_reduce_2,
  1, 27, :_reduce_3,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  5, 30, :_reduce_6,
  2, 31, :_reduce_7,
  1, 31, :_reduce_8,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  5, 33, :_reduce_11,
  2, 34, :_reduce_12,
  1, 34, :_reduce_13,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  5, 36, :_reduce_16,
  5, 29, :_reduce_17,
  2, 37, :_reduce_18,
  1, 37, :_reduce_19,
  2, 39, :_reduce_20,
  2, 39, :_reduce_21,
  2, 39, :_reduce_22,
  2, 39, :_reduce_23,
  2, 39, :_reduce_24,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 43, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 26, :_reduce_none,
  1, 38, :_reduce_34,
  1, 38, :_reduce_35,
  1, 38, :_reduce_36,
  1, 41, :_reduce_37,
  1, 42, :_reduce_38 ]

racc_reduce_n = 39

racc_shift_n = 67

racc_token_table = {
  false => 0,
  :error => 1,
  :STRING => 2,
  :VARIABLE_NAME => 3,
  :INTEGER => 4,
  "stylesheet" => 5,
  "{" => 6,
  "}" => 7,
  "page" => 8,
  "section" => 9,
  "question" => 10,
  "default" => 11,
  "color:" => 12,
  "font:" => 13,
  "font-size:" => 14,
  "widget:" => 15,
  "width:" => 16,
  "000000" => 17,
  "checkbox" => 18,
  "spinbox" => 19,
  "radio" => 20,
  "boolean" => 21,
  "integer" => 22,
  "string" => 23 }

racc_nt_base = 24

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "STRING",
  "VARIABLE_NAME",
  "INTEGER",
  "\"stylesheet\"",
  "\"{\"",
  "\"}\"",
  "\"page\"",
  "\"section\"",
  "\"question\"",
  "\"default\"",
  "\"color:\"",
  "\"font:\"",
  "\"font-size:\"",
  "\"widget:\"",
  "\"width:\"",
  "\"000000\"",
  "\"checkbox\"",
  "\"spinbox\"",
  "\"radio\"",
  "\"boolean\"",
  "\"integer\"",
  "\"string\"",
  "$start",
  "stylesheet",
  "variable_name",
  "stylesheet_rules",
  "stylesheet_rule",
  "default",
  "page",
  "page_rules",
  "page_rule",
  "section",
  "section_rules",
  "section_rule",
  "question",
  "declarations",
  "type",
  "declaration",
  "value",
  "integer",
  "string",
  "color",
  "widget" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
 result = Stylesheet.new(val[1], val[3]) 
    result
end

def _reduce_2(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_3(val, _values, result)
 result = [ val[0] ] 
    result
end

# reduce 4 omitted

# reduce 5 omitted

def _reduce_6(val, _values, result)
 result = Page.new(val[1], val[3]) 
    result
end

def _reduce_7(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_8(val, _values, result)
 result = [ val[0] ] 
    result
end

# reduce 9 omitted

# reduce 10 omitted

def _reduce_11(val, _values, result)
 result = Section.new(val[1], val[3]) 
    result
end

def _reduce_12(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_13(val, _values, result)
 result = [ val[0] ] 
    result
end

# reduce 14 omitted

# reduce 15 omitted

def _reduce_16(val, _values, result)
 result = Question.new(val[1], val[3]) 
    result
end

def _reduce_17(val, _values, result)
 result = Default.new(val[1], val[3]) 
    result
end

def _reduce_18(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_19(val, _values, result)
 result = [ val[0] ] 
    result
end

def _reduce_20(val, _values, result)
 result = ColorDeclaration.new(val[1]) 
    result
end

def _reduce_21(val, _values, result)
 result = FontDeclaration.new(val[1]) 
    result
end

def _reduce_22(val, _values, result)
 result = FontSizeDeclaration.new(val[1]) 
    result
end

def _reduce_23(val, _values, result)
 result = WidgitDeclaration.new(val[1]) 
    result
end

def _reduce_24(val, _values, result)
 result = WidthDeclaration.new(val[1]) 
    result
end

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

def _reduce_34(val, _values, result)
 result = BooleanType.new 
    result
end

def _reduce_35(val, _values, result)
 result = IntegerType.new 
    result
end

def _reduce_36(val, _values, result)
 result = StringType.new 
    result
end

def _reduce_37(val, _values, result)
 result = IntegerLiteral.new(val[0].to_i) 
    result
end

def _reduce_38(val, _values, result)
 result = StringLiteral.new(val[0][1..-2]) 
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module QLS
