form SalarySurvey{
	Str name "What is your name?";
	Int age "How old are you?";
	Dec height "Waht is your height?";
	Cur salary "How much is your annual salary?";
	Bool isMarried "Are you married?";
	
	if(5123123+5){
		Int employeeNr "What is your employee number?";
		Int employeeNr "What is your employee number?";
		Int employeeNr "What is your employee number?";
		Int employeeNr "What is your employee number?";
		
	} else {
		Int studentNr "What is your student number?";
	}
}
