#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'
module QLS
  class Parser < Racc::Parser


  require_relative '../ast/ast.rb'
  
  include AST


  def initialize(tokenizer)
    @tokenizer = tokenizer
    super()
  end

  def next_token
    @tokenizer.next_token
  end

  def parse
    do_parse
  end
##### State transition tables begin ###

racc_action_table = [
    58,     5,    57,    51,     5,    26,    41,    16,    13,    44,
    14,    15,    52,    53,    54,    55,    56,    64,    25,    32,
    14,    15,    38,    24,    32,    14,    15,    13,     5,    14,
    15,    32,    14,    15,    32,    14,    15,    21,    22,    23,
     5,     5,     5,     5,     7,    43,     6,    45,     5,     3,
     2 ]

racc_action_check = [
    43,    33,    43,    43,    37,    20,    33,     8,     8,    37,
     8,     8,    43,    43,    43,    43,    43,    59,    19,    59,
    59,    59,    27,    18,    27,    27,    27,     7,    14,     7,
     7,    45,    45,    45,    24,    24,    24,    15,    15,    15,
    25,    26,    13,    32,     4,    35,     3,    40,     2,     1,
     0 ]

racc_action_pointer = [
    44,    49,    45,    46,    37,   nil,   nil,    18,    -1,   nil,
   nil,   nil,   nil,    39,    25,    18,   nil,   nil,    16,    11,
    -2,   nil,   nil,   nil,    24,    37,    38,    14,   nil,   nil,
   nil,   nil,    40,    -2,   nil,    32,   nil,     1,   nil,   nil,
    40,   nil,   nil,    -2,   nil,    21,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     9,
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -41,   -41,   -41,   -41,   -41,   -35,    66,   -41,   -41,    -3,
    -4,    -5,    -6,   -41,   -41,   -41,    -1,    -2,   -41,   -41,
   -41,   -36,   -37,   -38,   -41,   -41,   -41,   -41,    -9,   -10,
   -11,   -12,   -41,   -41,   -22,   -41,   -24,   -41,    -7,    -8,
   -41,   -19,   -21,   -41,   -20,   -41,   -23,   -25,   -26,   -27,
   -28,   -29,   -30,   -31,   -32,   -33,   -34,   -39,   -40,   -41,
   -15,   -16,   -17,   -18,   -13,   -14 ]

racc_goto_table = [
    29,    31,     4,    29,    31,    63,    60,    42,    59,    28,
    27,    42,    39,    18,    19,    33,    37,     9,    17,    63,
    65,    61,    62,     8,    20,     1,    46,    47,    48,    49,
    50,   nil,    40,   nil,   nil,    61,    62 ]

racc_goto_check = [
     5,     7,     2,     5,     7,    10,    12,    15,    11,     9,
     8,    15,     9,     2,     2,    13,    13,     4,     4,    10,
    12,     5,     7,     3,    14,     1,    17,    18,    19,    20,
    21,   nil,     2,   nil,   nil,     5,     7 ]

racc_goto_pointer = [
   nil,    25,     0,    16,    10,   -24,   nil,   -23,   -14,   -15,
   -40,   -37,   -39,   -10,     9,   -26,   nil,   -17,   -16,   -15,
   -14,   -13 ]

racc_goto_default = [
   nil,   nil,    36,   nil,   nil,    10,    11,    12,   nil,   nil,
    30,   nil,   nil,   nil,   nil,    34,    35,   nil,   nil,   nil,
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 23, :_reduce_1,
  2, 25, :_reduce_2,
  1, 25, :_reduce_3,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  5, 28, :_reduce_7,
  2, 30, :_reduce_8,
  1, 30, :_reduce_9,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  5, 32, :_reduce_13,
  2, 33, :_reduce_14,
  1, 33, :_reduce_15,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  5, 29, :_reduce_19,
  5, 27, :_reduce_20,
  2, 35, :_reduce_21,
  1, 35, :_reduce_22,
  3, 37, :_reduce_23,
  1, 38, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 42, :_reduce_none,
  1, 43, :_reduce_30,
  1, 43, :_reduce_31,
  1, 43, :_reduce_32,
  1, 43, :_reduce_33,
  1, 43, :_reduce_34,
  1, 24, :_reduce_none,
  1, 36, :_reduce_36,
  1, 36, :_reduce_37,
  1, 36, :_reduce_38,
  1, 40, :_reduce_39,
  1, 41, :_reduce_40 ]

racc_reduce_n = 41

racc_shift_n = 66

racc_token_table = {
  false => 0,
  :error => 1,
  :STRING => 2,
  :VARIABLE_NAME => 3,
  :INTEGER => 4,
  :COLOR => 5,
  "stylesheet" => 6,
  "{" => 7,
  "}" => 8,
  "page" => 9,
  "section" => 10,
  "question" => 11,
  "default" => 12,
  ":" => 13,
  "checkbox" => 14,
  "spinbox" => 15,
  "radio" => 16,
  "dropdown" => 17,
  "text" => 18,
  "boolean" => 19,
  "integer" => 20,
  "string" => 21 }

racc_nt_base = 22

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "STRING",
  "VARIABLE_NAME",
  "INTEGER",
  "COLOR",
  "\"stylesheet\"",
  "\"{\"",
  "\"}\"",
  "\"page\"",
  "\"section\"",
  "\"question\"",
  "\"default\"",
  "\":\"",
  "\"checkbox\"",
  "\"spinbox\"",
  "\"radio\"",
  "\"dropdown\"",
  "\"text\"",
  "\"boolean\"",
  "\"integer\"",
  "\"string\"",
  "$start",
  "stylesheet",
  "variable_name",
  "stylesheet_rules",
  "stylesheet_rule",
  "default",
  "page",
  "question",
  "page_rules",
  "page_rule",
  "section",
  "section_rules",
  "section_rule",
  "declarations",
  "type",
  "declaration",
  "property",
  "value",
  "integer",
  "string",
  "color",
  "widget" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
 result = Stylesheet.new(val[1], val[3]) 
    result
end

def _reduce_2(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_3(val, _values, result)
 result = [ val[0] ] 
    result
end

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

def _reduce_7(val, _values, result)
 result = Page.new(val[1], val[3]) 
    result
end

def _reduce_8(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_9(val, _values, result)
 result = [ val[0] ] 
    result
end

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

def _reduce_13(val, _values, result)
 result = Section.new(val[1], val[3]) 
    result
end

def _reduce_14(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_15(val, _values, result)
 result = [ val[0] ] 
    result
end

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

def _reduce_19(val, _values, result)
 result = Question.new(val[1], val[3]) 
    result
end

def _reduce_20(val, _values, result)
 result = Default.new(val[1], val[3]) 
    result
end

def _reduce_21(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_22(val, _values, result)
 result = [ val[0] ] 
    result
end

def _reduce_23(val, _values, result)
 PropertyDeclaration.new(val[0], val[1]) 
    result
end

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

def _reduce_30(val, _values, result)
 result = Checkbox.new 
    result
end

def _reduce_31(val, _values, result)
 result = Spinbox.new 
    result
end

def _reduce_32(val, _values, result)
 result = YesNoRadio.new 
    result
end

def _reduce_33(val, _values, result)
 result = YesNoDropdown.new 
    result
end

def _reduce_34(val, _values, result)
 result = Text.new 
    result
end

# reduce 35 omitted

def _reduce_36(val, _values, result)
 result = BooleanType.new 
    result
end

def _reduce_37(val, _values, result)
 result = IntegerType.new 
    result
end

def _reduce_38(val, _values, result)
 result = StringType.new 
    result
end

def _reduce_39(val, _values, result)
 result = IntegerLiteral.new(val[0].to_i) 
    result
end

def _reduce_40(val, _values, result)
 result = StringLiteral.new(val[0][1..-2]) 
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module QLS
