/* This file was generated by SableCC (http://www.sablecc.org/). */

package QL.node;

import QL.analysis.*;

@SuppressWarnings("nls")
public final class ASingleStmtlist extends PStmtlist
{
    private PStmt _head_;

    public ASingleStmtlist()
    {
        // Constructor
    }

    public ASingleStmtlist(
        @SuppressWarnings("hiding") PStmt _head_)
    {
        // Constructor
        setHead(_head_);

    }

    @Override
    public Object clone()
    {
        return new ASingleStmtlist(
            cloneNode(this._head_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleStmtlist(this);
    }

    public PStmt getHead()
    {
        return this._head_;
    }

    public void setHead(PStmt node)
    {
        if(this._head_ != null)
        {
            this._head_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._head_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._head_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._head_ == child)
        {
            this._head_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._head_ == oldChild)
        {
            setHead((PStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
