/* This file was generated by SableCC (http://www.sablecc.org/). */

package QL.node;

import QL.analysis.*;

@SuppressWarnings("nls")
public final class TLbrace extends Token
{
    public TLbrace()
    {
        super.setText("{");
    }

    public TLbrace(int line, int pos)
    {
        super.setText("{");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLbrace(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLbrace(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLbrace text.");
    }
}
