#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'
module QL
  class Parser < Racc::Parser


  require_relative '../../ql'

  def initialize(tokenizer)
    @tokenizer = tokenizer
    super()
  end

  def next_token
    @tokenizer.next_token
  end

  def parse
    do_parse
  end
##### State transition tables begin ###

racc_action_table = [
    44,    45,    46,    47,    36,    41,    37,    38,    39,    40,
    42,    43,    15,    15,    44,    45,    16,    32,    33,    34,
     5,    14,    14,    62,    44,    45,    46,    47,    36,    41,
    37,    38,    39,    40,    42,    43,    15,     5,    28,    15,
     6,    15,     5,    28,    15,     5,    22,    35,    14,    29,
    30,    22,    19,    14,    29,    30,    15,     5,    28,    44,
    45,    15,     5,    28,    15,    20,    22,     3,    66,    29,
    30,    22,     2,    14,    29,    30,    15,     5,    28,   nil,
   nil,    15,     5,    28,   nil,   nil,    22,   nil,   nil,    29,
    30,    22,   nil,   nil,    29,    30,    15,     5,    28,   nil,
   nil,    15,     5,    28,   nil,   nil,    22,   nil,   nil,    29,
    30,    22,   nil,   nil,    29,    30,    15,     5,    28,   nil,
   nil,    15,     5,    28,   nil,   nil,    22,   nil,   nil,    29,
    30,    22,   nil,   nil,    29,    30,    15,     5,    28,   nil,
   nil,    15,     5,    28,   nil,   nil,    22,   nil,   nil,    29,
    30,    22,   nil,   nil,    29,    30,    15,     5,    28,   nil,
   nil,    15,     5,    28,    15,   nil,    22,   nil,    63,    29,
    30,    22,   nil,    14,    29,    30,    64,    44,    45,    46,
    47,    36,    41,    37,    38,    39,    40,   -37,   -37,    44,
    45,    46,    47,    36,    41,    37,    38,    39,    40,   -37,
   -37,    44,    45,    46,    47,   -37,   -37,   -37,   -37,   -37,
   -37,    44,    45,    46,    47,   -37,   -37,   -37,   -37,   -37,
   -37,    44,    45,    46,    47,   -37,   -37,   -37,   -37,   -37,
   -37,    44,    45,    46,    47,   -37,   -37,   -37,   -37,   -37,
   -37,    44,    45,    46,    47,   -37,   -37,   -37,   -37,   -37,
   -37,    44,    45,    46,    47,   -37,   -37,   -37,   -37,   -37,
   -37 ]

racc_action_check = [
    48,    48,    48,    48,    48,    48,    48,    48,    48,    48,
    48,    48,     7,     4,    61,    61,     7,    20,    20,    20,
     2,     7,     4,    48,    21,    21,    21,    21,    21,    21,
    21,    21,    21,    21,    21,    21,    41,    41,    41,    35,
     3,    46,    46,    46,    64,    11,    41,    21,    35,    41,
    41,    46,    14,    64,    46,    46,    45,    45,    45,    60,
    60,    44,    44,    44,    65,    18,    45,     1,    65,    45,
    45,    44,     0,    65,    44,    44,    43,    43,    43,   nil,
   nil,    47,    47,    47,   nil,   nil,    43,   nil,   nil,    43,
    43,    47,   nil,   nil,    47,    47,    40,    40,    40,   nil,
   nil,    19,    19,    19,   nil,   nil,    40,   nil,   nil,    40,
    40,    19,   nil,   nil,    19,    19,    39,    39,    39,   nil,
   nil,    42,    42,    42,   nil,   nil,    39,   nil,   nil,    39,
    39,    42,   nil,   nil,    42,    42,    22,    22,    22,   nil,
   nil,    38,    38,    38,   nil,   nil,    22,   nil,   nil,    22,
    22,    38,   nil,   nil,    38,    38,    37,    37,    37,   nil,
   nil,    36,    36,    36,    49,   nil,    37,   nil,    49,    37,
    37,    36,   nil,    49,    36,    36,    49,    56,    56,    56,
    56,    56,    56,    56,    56,    56,    56,    56,    56,    57,
    57,    57,    57,    57,    57,    57,    57,    57,    57,    57,
    57,    51,    51,    51,    51,    51,    51,    51,    51,    51,
    51,    55,    55,    55,    55,    55,    55,    55,    55,    55,
    55,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    54,    53,    53,    53,    53,    53,    53,    53,    53,    53,
    53,    52,    52,    52,    52,    52,    52,    52,    52,    52,
    52,    50,    50,    50,    50,    50,    50,    50,    50,    50,
    50 ]

racc_action_pointer = [
    55,    67,     5,    40,    -1,   nil,   nil,    -2,   nil,   nil,
   nil,    30,   nil,   nil,    28,   nil,   nil,   nil,    46,    87,
    -3,    22,   122,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    25,   147,   142,   127,   102,
    82,    22,   107,    62,    47,    42,    27,    67,    -2,   150,
   249,   199,   239,   229,   219,   209,   175,   187,   nil,   nil,
    57,    12,   nil,   nil,    30,    50,   nil ]

racc_action_default = [
   -37,   -37,   -37,   -37,   -37,    -7,    67,   -37,    -3,    -4,
    -5,   -37,   -11,   -12,   -37,   -34,    -1,    -2,   -37,   -37,
   -37,   -37,   -37,   -28,   -29,   -30,   -31,   -32,   -33,   -35,
   -36,    -6,    -8,    -9,   -10,   -37,   -37,   -37,   -37,   -37,
   -37,   -37,   -37,   -37,   -37,   -37,   -37,   -37,   -37,   -37,
   -15,   -16,   -17,   -18,   -19,   -20,   -21,   -22,   -23,   -24,
   -25,   -26,   -27,   -13,   -37,   -37,   -14 ]

racc_goto_table = [
    11,    17,     7,    11,     4,    31,     1,   nil,   nil,   nil,
   nil,   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,
   nil,    11,    48,    49,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    17,   nil,    11,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,   nil,    17,
    11,    11,    65 ]

racc_goto_check = [
     7,     4,     3,     7,     2,     8,     1,   nil,   nil,   nil,
   nil,   nil,   nil,     2,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    11,
   nil,     7,    11,     3,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     4,   nil,     7,    11,    11,    11,    11,
    11,    11,    11,    11,    11,    11,    11,    11,   nil,     4,
     7,     7,     3 ]

racc_goto_pointer = [
   nil,     6,     2,    -2,    -6,   nil,   nil,    -4,   -15,   nil,
   nil,    10,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,    24,   nil,     8,     9,    10,    26,   nil,    12,
    13,   nil,    23,    25,    27 ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 30, :_reduce_1,
  2, 32, :_reduce_2,
  1, 32, :_reduce_3,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  4, 34, :_reduce_6,
  1, 31, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  6, 38, :_reduce_13,
  8, 39, :_reduce_14,
  3, 40, :_reduce_15,
  3, 40, :_reduce_16,
  3, 40, :_reduce_17,
  3, 40, :_reduce_18,
  3, 40, :_reduce_19,
  3, 40, :_reduce_20,
  3, 40, :_reduce_21,
  3, 40, :_reduce_22,
  3, 40, :_reduce_23,
  3, 40, :_reduce_24,
  3, 40, :_reduce_25,
  3, 40, :_reduce_26,
  3, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_29,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 42, :_reduce_33,
  1, 36, :_reduce_34,
  1, 43, :_reduce_35,
  1, 43, :_reduce_36 ]

racc_reduce_n = 37

racc_shift_n = 67

racc_token_table = {
  false => 0,
  :error => 1,
  "*" => 2,
  "/" => 3,
  "+" => 4,
  "-" => 5,
  "==" => 6,
  "!=" => 7,
  "<=" => 8,
  "<" => 9,
  ">=" => 10,
  ">" => 11,
  "&&" => 12,
  "||" => 13,
  :STRING => 14,
  :VARIABLE_NAME => 15,
  :INTEGER => 16,
  "form" => 17,
  "end" => 18,
  ":" => 19,
  "boolean" => 20,
  "integer" => 21,
  "string" => 22,
  "if" => 23,
  "(" => 24,
  ")" => 25,
  "else" => 26,
  "true" => 27,
  "false" => 28 }

racc_nt_base = 29

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"==\"",
  "\"!=\"",
  "\"<=\"",
  "\"<\"",
  "\">=\"",
  "\">\"",
  "\"&&\"",
  "\"||\"",
  "STRING",
  "VARIABLE_NAME",
  "INTEGER",
  "\"form\"",
  "\"end\"",
  "\":\"",
  "\"boolean\"",
  "\"integer\"",
  "\"string\"",
  "\"if\"",
  "\"(\"",
  "\")\"",
  "\"else\"",
  "\"true\"",
  "\"false\"",
  "$start",
  "form",
  "variable_name",
  "statements",
  "statement",
  "question",
  "conditional",
  "string",
  "type",
  "if",
  "if_else",
  "expression",
  "constant",
  "integer",
  "boolean" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
 result = Form.new(name: val[1], statements: val[2]) 
    result
end

def _reduce_2(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_3(val, _values, result)
 result = [ val[0] ] 
    result
end

# reduce 4 omitted

# reduce 5 omitted

def _reduce_6(val, _values, result)
 result = Question.new(description: val[0], variable_name: val[1], type: val[3].to_sym) 
    result
end

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

def _reduce_13(val, _values, result)
 result = If.new(expression: val[2], statements: val[4]) 
    result
end

def _reduce_14(val, _values, result)
 result = IfElse.new(expression: val[2], statements_true: val[4], statements_false: val[6]) 
    result
end

def _reduce_15(val, _values, result)
 result = Equal.new(val[0], val[2]) 
    result
end

def _reduce_16(val, _values, result)
 result = LessThanOrEqualTo.new(val[0], val[2]) 
    result
end

def _reduce_17(val, _values, result)
 result = LessThan.new(val[0], val[2]) 
    result
end

def _reduce_18(val, _values, result)
 result = GreaterThanOrEqualTo.new(val[0], val[2]) 
    result
end

def _reduce_19(val, _values, result)
 result = GreaterThan.new(val[0], val[2]) 
    result
end

def _reduce_20(val, _values, result)
 result = Inequal.new(val[0], val[2]) 
    result
end

def _reduce_21(val, _values, result)
 result = And.new(val[0], val[2]) 
    result
end

def _reduce_22(val, _values, result)
 result = Or.new(val[0], val[2]) 
    result
end

def _reduce_23(val, _values, result)
 result = Multiplication.new(val[0], val[2]) 
    result
end

def _reduce_24(val, _values, result)
 result = Division.new(val[0], val[2]) 
    result
end

def _reduce_25(val, _values, result)
 result = Plus.new(val[0], val[2]) 
    result
end

def _reduce_26(val, _values, result)
 result = Minus.new(val[0], val[2]) 
    result
end

# reduce 27 omitted

# reduce 28 omitted

def _reduce_29(val, _values, result)
 result = Variable.new(val[0]) 
    result
end

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

def _reduce_33(val, _values, result)
 result = IntegerLiteral.new(val[0].to_i) 
    result
end

def _reduce_34(val, _values, result)
 result = StringLiteral.new(val[0][1..-2]) 
    result
end

def _reduce_35(val, _values, result)
 result = BooleanLiteral.new(true) 
    result
end

def _reduce_36(val, _values, result)
 result = BooleanLiteral.new(false) 
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module QL
