#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'
module QL
  class Parser < Racc::Parser


  require_relative '../ql'

  def initialize tokenizer
    @tokenizer = tokenizer
    super()
  end

  def next_token
    @tokenizer.next_token
  end

  def parse
    do_parse
  end
##### State transition tables begin ###

racc_action_table = [
    15,     5,    28,    15,     5,    28,    15,     5,    28,     6,
    22,    19,     5,    22,    15,    15,    22,    15,     5,    28,
    15,     5,    28,    14,    14,    29,    30,    22,    29,    30,
    22,    29,    30,    20,    15,     5,    28,    15,     5,    28,
     5,     3,    29,    30,    22,    29,    30,    22,    15,     5,
    28,    15,     5,    28,    15,     5,    28,     2,    22,    29,
    30,    22,    29,    30,    22,    15,     5,    28,    15,     5,
    28,   nil,    15,    29,    30,    22,    29,    30,    22,    29,
    30,    14,    15,     5,    28,    15,     5,    28,   nil,   nil,
    29,    30,    22,    29,    30,    22,    15,    15,   nil,   nil,
    16,    63,    32,    33,    34,    14,    14,    29,    30,    64,
    29,    30,    62,   nil,    36,    37,    38,    39,    40,    41,
    42,    43,    44,    45,    46,    47,    35,   nil,    36,    37,
    38,    39,    40,    41,    42,    43,    44,    45,    46,    47,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    36,    37,    38,    39,    40,    41,
    42,    43,    44,    45,    46,    47,    36,    37,    38,    39,
    40,    41,    42,    43,    44,    45,    46,    47,    36,    37,
    38,    39,    40,    41,    42,    43,    44,    45,    46,    47,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    36,    37,    38,    39,    40,    41,
    42,    43,    44,    45,    46,    47,    36,    37,    38,    39,
    40,    41,    42,    43,    44,    45,    46,    47,    36,    37,
    38,    39,    40,    41,    42,    43,    44,    45,    46,    47,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    15,   nil,   nil,   nil,    66,   nil,
   nil,   nil,   nil,    14 ]

racc_action_check = [
    43,    43,    43,    47,    47,    47,    46,    46,    46,     3,
    43,    14,    11,    47,    64,     4,    46,    45,    45,    45,
    44,    44,    44,    64,     4,    43,    43,    45,    47,    47,
    44,    46,    46,    18,    42,    42,    42,    41,    41,    41,
     2,     1,    45,    45,    42,    44,    44,    41,    40,    40,
    40,    39,    39,    39,    19,    19,    19,     0,    40,    42,
    42,    39,    41,    41,    19,    36,    36,    36,    37,    37,
    37,   nil,    35,    40,    40,    36,    39,    39,    37,    19,
    19,    35,    22,    22,    22,    38,    38,    38,   nil,   nil,
    36,    36,    22,    37,    37,    38,     7,    49,   nil,   nil,
     7,    49,    20,    20,    20,     7,    49,    22,    22,    49,
    38,    38,    48,   nil,    48,    48,    48,    48,    48,    48,
    48,    48,    48,    48,    48,    48,    21,   nil,    21,    21,
    21,    21,    21,    21,    21,    21,    21,    21,    21,    21,
    55,    55,    55,    55,    55,    55,    55,    55,    55,    55,
    55,    55,    58,    58,    58,    58,    58,    58,    58,    58,
    58,    58,    58,    58,    59,    59,    59,    59,    59,    59,
    59,    59,    59,    59,    59,    59,    53,    53,    53,    53,
    53,    53,    53,    53,    53,    53,    53,    53,    57,    57,
    57,    57,    57,    57,    57,    57,    57,    57,    57,    57,
    52,    52,    52,    52,    52,    52,    52,    52,    52,    52,
    52,    52,    50,    50,    50,    50,    50,    50,    50,    50,
    50,    50,    50,    50,    61,    61,    61,    61,    61,    61,
    61,    61,    61,    61,    61,    61,    51,    51,    51,    51,
    51,    51,    51,    51,    51,    51,    51,    51,    56,    56,
    56,    56,    56,    56,    56,    56,    56,    56,    56,    56,
    54,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    54,    54,    60,    60,    60,    60,    60,    60,    60,    60,
    60,    60,    60,    60,    65,   nil,   nil,   nil,    65,   nil,
   nil,   nil,   nil,    65 ]

racc_action_pointer = [
    52,    41,    37,     9,    13,   nil,   nil,    94,   nil,   nil,
   nil,     9,   nil,   nil,    -1,   nil,   nil,   nil,    26,    52,
    94,   113,    80,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    70,    63,    66,    83,    49,
    46,    35,    32,    -2,    18,    15,     4,     1,    99,    95,
   197,   221,   185,   161,   245,   125,   233,   173,   137,   149,
   257,   209,   nil,   nil,    12,   282,   nil ]

racc_action_default = [
   -37,   -37,   -37,   -37,   -37,    -7,    67,   -37,    -3,    -4,
    -5,   -37,   -11,   -12,   -37,   -34,    -1,    -2,   -37,   -37,
   -37,   -37,   -37,   -28,   -29,   -30,   -31,   -32,   -33,   -35,
   -36,    -6,    -8,    -9,   -10,   -37,   -37,   -37,   -37,   -37,
   -37,   -37,   -37,   -37,   -37,   -37,   -37,   -37,   -37,   -37,
   -15,   -16,   -17,   -18,   -19,   -20,   -21,   -22,   -23,   -24,
   -25,   -26,   -27,   -13,   -37,   -37,   -14 ]

racc_goto_table = [
    11,    17,     7,    11,     4,    31,     1,   nil,   nil,   nil,
   nil,   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,
   nil,    11,    48,    49,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    17,   nil,    11,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,   nil,    17,
    11,    11,    65 ]

racc_goto_check = [
     7,     4,     3,     7,     2,     8,     1,   nil,   nil,   nil,
   nil,   nil,   nil,     2,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    11,
   nil,     7,    11,     3,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     4,   nil,     7,    11,    11,    11,    11,
    11,    11,    11,    11,    11,    11,    11,    11,   nil,     4,
     7,     7,     3 ]

racc_goto_pointer = [
   nil,     6,     2,    -2,    -6,   nil,   nil,    -4,   -15,   nil,
   nil,    10,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,    24,   nil,     8,     9,    10,    26,   nil,    12,
    13,   nil,    23,    25,    27 ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 30, :_reduce_1,
  2, 32, :_reduce_2,
  1, 32, :_reduce_3,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  4, 34, :_reduce_6,
  1, 31, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  6, 38, :_reduce_13,
  8, 39, :_reduce_14,
  3, 40, :_reduce_15,
  3, 40, :_reduce_16,
  3, 40, :_reduce_17,
  3, 40, :_reduce_18,
  3, 40, :_reduce_19,
  3, 40, :_reduce_20,
  3, 40, :_reduce_21,
  3, 40, :_reduce_22,
  3, 40, :_reduce_23,
  3, 40, :_reduce_24,
  3, 40, :_reduce_25,
  3, 40, :_reduce_26,
  3, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_29,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 42, :_reduce_33,
  1, 36, :_reduce_34,
  1, 43, :_reduce_35,
  1, 43, :_reduce_36 ]

racc_reduce_n = 37

racc_shift_n = 67

racc_token_table = {
  false => 0,
  :error => 1,
  :STRING => 2,
  :VARIABLE_NAME => 3,
  :INTEGER => 4,
  "form" => 5,
  "end" => 6,
  ":" => 7,
  "boolean" => 8,
  "integer" => 9,
  "string" => 10,
  "if" => 11,
  "(" => 12,
  ")" => 13,
  "else" => 14,
  "==" => 15,
  "<=" => 16,
  "<" => 17,
  ">=" => 18,
  ">" => 19,
  "!=" => 20,
  "&&" => 21,
  "||" => 22,
  "*" => 23,
  "/" => 24,
  "+" => 25,
  "-" => 26,
  "true" => 27,
  "false" => 28 }

racc_nt_base = 29

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "STRING",
  "VARIABLE_NAME",
  "INTEGER",
  "\"form\"",
  "\"end\"",
  "\":\"",
  "\"boolean\"",
  "\"integer\"",
  "\"string\"",
  "\"if\"",
  "\"(\"",
  "\")\"",
  "\"else\"",
  "\"==\"",
  "\"<=\"",
  "\"<\"",
  "\">=\"",
  "\">\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"true\"",
  "\"false\"",
  "$start",
  "form",
  "variable_name",
  "statements",
  "statement",
  "question",
  "conditional",
  "string",
  "type",
  "if",
  "if_else",
  "expression",
  "constant",
  "integer",
  "boolean" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
 result = Form.new(name: val[1], statements: val[2]) 
    result
end

def _reduce_2(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_3(val, _values, result)
 result = [ val[0] ] 
    result
end

# reduce 4 omitted

# reduce 5 omitted

def _reduce_6(val, _values, result)
 result = Question.new(description: val[0], variable_name: val[1], type: val[3]) 
    result
end

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

def _reduce_13(val, _values, result)
 result = If.new(expression: val[2], statements: val[4]) 
    result
end

def _reduce_14(val, _values, result)
 result = IfElse.new(expression: val[2], statements_true: val[4], statements_false: val[6]) 
    result
end

def _reduce_15(val, _values, result)
 result = Equal.new(val[0], val[2]) 
    result
end

def _reduce_16(val, _values, result)
 result = LessThanOrEqualTo.new(val[0], val[2]) 
    result
end

def _reduce_17(val, _values, result)
 result = LessThan.new(val[0], val[2]) 
    result
end

def _reduce_18(val, _values, result)
 result = GreaterThanOrEqualTo.new(val[0], val[2]) 
    result
end

def _reduce_19(val, _values, result)
 result = GreaterThan.new(val[0], val[2]) 
    result
end

def _reduce_20(val, _values, result)
 result = Inequal.new(val[0], val[2]) 
    result
end

def _reduce_21(val, _values, result)
 result = And.new(val[0], val[2]) 
    result
end

def _reduce_22(val, _values, result)
 result = Or.new(val[0], val[2]) 
    result
end

def _reduce_23(val, _values, result)
 result = Multiplication.new(val[0], val[2]) 
    result
end

def _reduce_24(val, _values, result)
 result = Division.new(val[0], val[2]) 
    result
end

def _reduce_25(val, _values, result)
 result = Plus.new(val[0], val[2]) 
    result
end

def _reduce_26(val, _values, result)
 result = Minus.new(val[0], val[2]) 
    result
end

# reduce 27 omitted

# reduce 28 omitted

def _reduce_29(val, _values, result)
 result = Variable.new(val[0]) 
    result
end

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

def _reduce_33(val, _values, result)
 result = IntegerLiteral.new(val[0].to_i) 
    result
end

def _reduce_34(val, _values, result)
 result = StringLiteral.new(val[0][1..-2]) 
    result
end

def _reduce_35(val, _values, result)
 result = BooleanLiteral.new(true) 
    result
end

def _reduce_36(val, _values, result)
 result = BooleanLiteral.new(false) 
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module QL
