#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'
module QL
  class Parser < Racc::Parser


  require_relative 'form'
  require_relative 'variable'
  require_relative 'expression'
  require_relative 'visitor'

  def initialize tokenizer
    @tokenizer = tokenizer
    super()
  end

  def next_token
    @tokenizer.next_token
  end

  def parse
    do_parse
  end
##### State transition tables begin ###

racc_action_table = [
    32,     6,    33,    34,    35,    36,    37,    38,    39,    40,
    41,    42,    43,    44,    59,    21,    33,    34,    35,    36,
    37,    38,    39,    40,    41,    42,    43,    44,    15,    20,
    27,    20,    60,    29,    30,    31,    22,    14,    24,     5,
    61,    33,    34,    35,    36,    37,    38,    39,    40,    41,
    42,    43,    44,    33,    34,    35,    36,    37,    38,    39,
    40,    41,    42,    43,    44,    33,    34,    35,    36,    37,
    38,    39,    40,    41,    42,    43,    44,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    33,    34,    35,    36,    37,    38,    39,    40,    41,
    42,    43,    44,    33,    34,    35,    36,    37,    38,    39,
    40,    41,    42,    43,    44,    33,    34,    35,    36,    37,
    38,    39,    40,    41,    42,    43,    44,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    33,    34,    35,    36,    37,    38,    39,    40,    41,
    42,    43,    44,    33,    34,    35,    36,    37,    38,    39,
    40,    41,    42,    43,    44,    20,    27,    20,    27,    20,
    27,    20,    27,     3,    24,     2,    24,   nil,    24,   nil,
    24,    20,    27,    20,    27,    20,    27,    20,    27,   nil,
    24,   nil,    24,    15,    24,   nil,    24,    20,    27,    20,
    27,   nil,    14,    20,    27,    15,    24,    15,    24,    20,
    27,    16,    24,    15,    14,    15,    14,   nil,    24,    63,
    20,    27,    14,   nil,    14,   nil,   nil,   nil,   nil,    24 ]

racc_action_check = [
    23,     3,    23,    23,    23,    23,    23,    23,    23,    23,
    23,    23,    23,    23,    45,    14,    45,    45,    45,    45,
    45,    45,    45,    45,    45,    45,    45,    45,    46,    35,
    35,    11,    46,    22,    22,    22,    19,    46,    35,     2,
    46,    55,    55,    55,    55,    55,    55,    55,    55,    55,
    55,    55,    55,    49,    49,    49,    49,    49,    49,    49,
    49,    49,    49,    49,    49,    48,    48,    48,    48,    48,
    48,    48,    48,    48,    48,    48,    48,    56,    56,    56,
    56,    56,    56,    56,    56,    56,    56,    56,    56,    57,
    57,    57,    57,    57,    57,    57,    57,    57,    57,    57,
    57,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    54,    54,    54,    47,    47,    47,    47,    47,    47,    47,
    47,    47,    47,    47,    47,    53,    53,    53,    53,    53,
    53,    53,    53,    53,    53,    53,    53,    51,    51,    51,
    51,    51,    51,    51,    51,    51,    51,    51,    51,    58,
    58,    58,    58,    58,    58,    58,    58,    58,    58,    58,
    58,    50,    50,    50,    50,    50,    50,    50,    50,    50,
    50,    50,    50,    52,    52,    52,    52,    52,    52,    52,
    52,    52,    52,    52,    52,    34,    34,    36,    36,    37,
    37,    38,    38,     1,    34,     0,    36,   nil,    37,   nil,
    38,    39,    39,    33,    33,    41,    41,    42,    42,   nil,
    39,   nil,    33,    32,    41,   nil,    42,    43,    43,    44,
    44,   nil,    32,    24,    24,     4,    43,     7,    44,    21,
    21,     7,    24,    61,     4,    62,     7,   nil,    21,    62,
    40,    40,    61,   nil,    62,   nil,   nil,   nil,   nil,    40 ]

racc_action_pointer = [
   190,   193,    36,     1,   223,   nil,   nil,   225,   nil,   nil,
   nil,    28,   nil,   nil,     3,   nil,   nil,   nil,   nil,    29,
   nil,   226,    25,   -13,   220,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   211,   200,   182,    26,   184,   186,   188,   198,
   237,   202,   204,   214,   216,     1,    26,    98,    50,    38,
   146,   122,   158,   110,    86,    26,    62,    74,   134,   nil,
   nil,   231,   233,   nil ]

racc_action_default = [
   -39,   -39,   -39,   -39,   -39,    -2,    64,   -39,    -4,    -5,
    -6,   -39,   -13,   -14,   -39,   -36,    -1,    -3,    -7,   -39,
    -9,   -39,   -39,   -39,   -39,   -30,   -31,   -35,    -8,   -10,
   -11,   -12,   -39,   -39,   -39,   -39,   -39,   -39,   -39,   -39,
   -39,   -39,   -39,   -39,   -39,   -39,   -39,   -17,   -18,   -19,
   -20,   -21,   -22,   -23,   -24,   -25,   -26,   -27,   -28,   -29,
   -15,   -39,   -39,   -16 ]

racc_goto_table = [
     7,    17,    23,    18,     4,    45,    19,    28,     1,   nil,
   nil,   nil,   nil,   nil,    47,    48,    49,    50,    51,    52,
    53,    54,    55,    56,    57,    58,   nil,   nil,    46,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    17,    62 ]

racc_goto_check = [
     3,     4,    13,     8,     2,    13,     9,    10,     1,   nil,
   nil,   nil,   nil,   nil,    13,    13,    13,    13,    13,    13,
    13,    13,    13,    13,    13,    13,   nil,   nil,     3,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     4,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     4,     3 ]

racc_goto_pointer = [
   nil,     8,     2,    -4,    -6,   nil,   nil,   nil,    -8,    -5,
   -15,   nil,   nil,   -19,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     8,     9,    10,    11,   nil,    26,
   nil,    12,    13,   nil,    25,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 30, :_reduce_1,
  1, 31, :_reduce_none,
  2, 32, :_reduce_3,
  1, 32, :_reduce_4,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  2, 34, :_reduce_7,
  3, 37, :_reduce_8,
  1, 38, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  6, 40, :_reduce_15,
  8, 41, :_reduce_16,
  3, 42, :_reduce_17,
  3, 42, :_reduce_18,
  3, 42, :_reduce_19,
  3, 42, :_reduce_20,
  3, 42, :_reduce_21,
  3, 42, :_reduce_22,
  3, 42, :_reduce_23,
  3, 42, :_reduce_24,
  3, 42, :_reduce_25,
  3, 42, :_reduce_26,
  3, 42, :_reduce_27,
  3, 42, :_reduce_28,
  3, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_31,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 43, :_reduce_35,
  1, 36, :_reduce_36,
  1, 45, :_reduce_37,
  1, 45, :_reduce_38 ]

racc_reduce_n = 39

racc_shift_n = 64

racc_token_table = {
  false => 0,
  :error => 1,
  :STRING => 2,
  :VARIABLE_NAME => 3,
  :INTEGER => 4,
  "form" => 5,
  "end" => 6,
  ":" => 7,
  "boolean" => 8,
  "integer" => 9,
  "string" => 10,
  "if" => 11,
  "(" => 12,
  ")" => 13,
  "else" => 14,
  "==" => 15,
  "<=" => 16,
  "<" => 17,
  ">=" => 18,
  ">" => 19,
  "!=" => 20,
  "&&" => 21,
  "||" => 22,
  "*" => 23,
  "/" => 24,
  "+" => 25,
  "-" => 26,
  "true" => 27,
  "false" => 28 }

racc_nt_base = 29

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "STRING",
  "VARIABLE_NAME",
  "INTEGER",
  "\"form\"",
  "\"end\"",
  "\":\"",
  "\"boolean\"",
  "\"integer\"",
  "\"string\"",
  "\"if\"",
  "\"(\"",
  "\")\"",
  "\"else\"",
  "\"==\"",
  "\"<=\"",
  "\"<\"",
  "\">=\"",
  "\">\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"true\"",
  "\"false\"",
  "$start",
  "form",
  "form_name",
  "statements",
  "statement",
  "question",
  "conditional",
  "string",
  "variable_definition",
  "variable_name",
  "type",
  "if",
  "if_else",
  "expression",
  "integer",
  "constant",
  "boolean" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
 result = Form.new(name: val[1], statements: val[2]) 
    result
end

# reduce 2 omitted

def _reduce_3(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_4(val, _values, result)
 result = [ val[0] ] 
    result
end

# reduce 5 omitted

# reduce 6 omitted

def _reduce_7(val, _values, result)
 result = Question.new(description: val[0], variable_definition: val[1]) 
    result
end

def _reduce_8(val, _values, result)
 result = VariableDefinition.new(name: val[0], type: val[2]) 
    result
end

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

def _reduce_15(val, _values, result)
 result = If.new(expression: val[2], statements: val[4]) 
    result
end

def _reduce_16(val, _values, result)
 result = IfElse.new(expression: val[2], statements_true: val[4], statements_false: val[6]) 
    result
end

def _reduce_17(val, _values, result)
 result = Equal.new(val[0], val[2]) 
    result
end

def _reduce_18(val, _values, result)
 result = LessThanOrEqualTo.new(val[0], val[2]) 
    result
end

def _reduce_19(val, _values, result)
 result = LessThan.new(val[0], val[2]) 
    result
end

def _reduce_20(val, _values, result)
 result = GreaterThanOrEqualTo.new(val[0], val[2]) 
    result
end

def _reduce_21(val, _values, result)
 result = GreaterThan.new(val[0], val[2]) 
    result
end

def _reduce_22(val, _values, result)
 result = Inequal.new(val[0], val[2]) 
    result
end

def _reduce_23(val, _values, result)
 result = And.new(val[0], val[2]) 
    result
end

def _reduce_24(val, _values, result)
 result = Or.new(val[0], val[2]) 
    result
end

def _reduce_25(val, _values, result)
 result = Multiplication.new(val[0], val[2]) 
    result
end

def _reduce_26(val, _values, result)
 result = Division.new(val[0], val[2]) 
    result
end

def _reduce_27(val, _values, result)
 result = Plus.new(val[0], val[2]) 
    result
end

def _reduce_28(val, _values, result)
 result = Minus.new(val[0], val[2]) 
    result
end

# reduce 29 omitted

# reduce 30 omitted

def _reduce_31(val, _values, result)
 result = Variable.new(val[0]) 
    result
end

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

def _reduce_35(val, _values, result)
 result = val[0].to_i 
    result
end

def _reduce_36(val, _values, result)
 result = val[0][1..-2] 
    result
end

def _reduce_37(val, _values, result)
 result = true 
    result
end

def _reduce_38(val, _values, result)
 result = false 
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module QL
