#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'
module QL
  class Parser < Racc::Parser


  require_relative '../ast/ast.rb'
  include QL::AST


  def initialize(tokenizer)
    @tokenizer = tokenizer
    super()
  end

  def next_token
    @tokenizer.next_token
  end

  def parse
    do_parse
  end
##### State transition tables begin ###

racc_action_table = [
    45,    46,    47,    48,    37,    42,    38,    39,    40,    41,
    43,    44,    12,    12,    45,    46,    16,    33,    34,    35,
     5,    15,    15,    63,    45,    46,    47,    48,    37,    42,
    38,    39,    40,    41,    43,    44,    29,     5,    28,    12,
     6,    29,     5,    28,    12,     5,    22,    36,    15,    30,
    31,    22,    19,    15,    30,    31,    29,     5,    28,    45,
    46,    29,     5,    28,    12,    20,    22,     3,    67,    30,
    31,    22,     2,    15,    30,    31,    29,     5,    28,   nil,
   nil,    29,     5,    28,   nil,   nil,    22,   nil,   nil,    30,
    31,    22,   nil,   nil,    30,    31,    29,     5,    28,   nil,
   nil,    29,     5,    28,   nil,   nil,    22,   nil,   nil,    30,
    31,    22,   nil,   nil,    30,    31,    29,     5,    28,   nil,
   nil,    29,     5,    28,   nil,   nil,    22,   nil,   nil,    30,
    31,    22,   nil,   nil,    30,    31,    29,     5,    28,   nil,
   nil,    29,     5,    28,   nil,   nil,    22,   nil,   nil,    30,
    31,    22,   nil,   nil,    30,    31,    29,     5,    28,   nil,
   nil,    29,     5,    28,    12,   nil,    22,   nil,    64,    30,
    31,    22,   nil,    15,    30,    31,    65,    45,    46,    47,
    48,    37,    42,    38,    39,    40,    41,   -38,   -38,    45,
    46,    47,    48,    37,    42,    38,    39,    40,    41,   -38,
   -38,    45,    46,    47,    48,   -38,   -38,   -38,   -38,   -38,
   -38,    45,    46,    47,    48,   -38,   -38,   -38,   -38,   -38,
   -38,    45,    46,    47,    48,   -38,   -38,   -38,   -38,   -38,
   -38,    45,    46,    47,    48,   -38,   -38,   -38,   -38,   -38,
   -38,    45,    46,    47,    48,   -38,   -38,   -38,   -38,   -38,
   -38,    45,    46,    47,    48,   -38,   -38,   -38,   -38,   -38,
   -38 ]

racc_action_check = [
    49,    49,    49,    49,    49,    49,    49,    49,    49,    49,
    49,    49,     7,     4,    62,    62,     7,    20,    20,    20,
     2,     7,     4,    49,    21,    21,    21,    21,    21,    21,
    21,    21,    21,    21,    21,    21,    42,    42,    42,    36,
     3,    47,    47,    47,    65,    11,    42,    21,    36,    42,
    42,    47,    15,    65,    47,    47,    46,    46,    46,    61,
    61,    45,    45,    45,    66,    18,    46,     1,    66,    46,
    46,    45,     0,    66,    45,    45,    44,    44,    44,   nil,
   nil,    48,    48,    48,   nil,   nil,    44,   nil,   nil,    44,
    44,    48,   nil,   nil,    48,    48,    41,    41,    41,   nil,
   nil,    19,    19,    19,   nil,   nil,    41,   nil,   nil,    41,
    41,    19,   nil,   nil,    19,    19,    40,    40,    40,   nil,
   nil,    43,    43,    43,   nil,   nil,    40,   nil,   nil,    40,
    40,    43,   nil,   nil,    43,    43,    22,    22,    22,   nil,
   nil,    39,    39,    39,   nil,   nil,    22,   nil,   nil,    22,
    22,    39,   nil,   nil,    39,    39,    38,    38,    38,   nil,
   nil,    37,    37,    37,    50,   nil,    38,   nil,    50,    38,
    38,    37,   nil,    50,    37,    37,    50,    57,    57,    57,
    57,    57,    57,    57,    57,    57,    57,    57,    57,    58,
    58,    58,    58,    58,    58,    58,    58,    58,    58,    58,
    58,    52,    52,    52,    52,    52,    52,    52,    52,    52,
    52,    56,    56,    56,    56,    56,    56,    56,    56,    56,
    56,    55,    55,    55,    55,    55,    55,    55,    55,    55,
    55,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    54,    53,    53,    53,    53,    53,    53,    53,    53,    53,
    53,    51,    51,    51,    51,    51,    51,    51,    51,    51,
    51 ]

racc_action_pointer = [
    55,    67,     5,    40,    -1,   nil,   nil,    -2,   nil,   nil,
   nil,    30,   nil,   nil,   nil,    28,   nil,   nil,    46,    87,
    -3,    22,   122,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    25,   147,   142,   127,
   102,    82,    22,   107,    62,    47,    42,    27,    67,    -2,
   150,   249,   199,   239,   229,   219,   209,   175,   187,   nil,
   nil,    57,    12,   nil,   nil,    30,    50,   nil ]

racc_action_default = [
   -38,   -38,   -38,   -38,   -38,    -8,    68,   -38,    -3,    -4,
    -5,   -38,    -7,   -12,   -13,   -38,    -1,    -2,   -38,   -38,
   -38,   -38,   -38,   -29,   -30,   -31,   -32,   -33,   -34,   -35,
   -36,   -37,    -6,    -9,   -10,   -11,   -38,   -38,   -38,   -38,
   -38,   -38,   -38,   -38,   -38,   -38,   -38,   -38,   -38,   -38,
   -38,   -16,   -17,   -18,   -19,   -20,   -21,   -22,   -23,   -24,
   -25,   -26,   -27,   -28,   -14,   -38,   -38,   -15 ]

racc_goto_table = [
     7,    17,    21,     4,    32,    49,     1,   nil,   nil,   nil,
   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    51,    52,    53,    54,    55,    56,    57,    58,    59,    60,
    61,    62,    50,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    17,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    17,    66 ]

racc_goto_check = [
     3,     4,    11,     2,     8,    11,     1,   nil,   nil,   nil,
   nil,   nil,     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    11,    11,    11,    11,    11,    11,    11,    11,    11,    11,
    11,    11,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     4,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     4,     3 ]

racc_goto_pointer = [
   nil,     6,     1,    -4,    -6,   nil,   nil,   nil,   -16,   nil,
   nil,   -17,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,    24,   nil,     8,     9,    10,    11,   nil,    13,
    14,   nil,    23,    25,    26,    27 ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 30, :_reduce_1,
  2, 32, :_reduce_2,
  1, 32, :_reduce_3,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  4, 34, :_reduce_6,
  1, 36, :_reduce_7,
  1, 31, :_reduce_none,
  1, 37, :_reduce_9,
  1, 37, :_reduce_10,
  1, 37, :_reduce_11,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  6, 38, :_reduce_14,
  8, 39, :_reduce_15,
  3, 40, :_reduce_16,
  3, 40, :_reduce_17,
  3, 40, :_reduce_18,
  3, 40, :_reduce_19,
  3, 40, :_reduce_20,
  3, 40, :_reduce_21,
  3, 40, :_reduce_22,
  3, 40, :_reduce_23,
  3, 40, :_reduce_24,
  3, 40, :_reduce_25,
  3, 40, :_reduce_26,
  3, 40, :_reduce_27,
  3, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_30,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 42, :_reduce_34,
  1, 43, :_reduce_35,
  1, 44, :_reduce_36,
  1, 44, :_reduce_37 ]

racc_reduce_n = 38

racc_shift_n = 68

racc_token_table = {
  false => 0,
  :error => 1,
  "*" => 2,
  "/" => 3,
  "+" => 4,
  "-" => 5,
  "==" => 6,
  "!=" => 7,
  "<=" => 8,
  "<" => 9,
  ">=" => 10,
  ">" => 11,
  "&&" => 12,
  "||" => 13,
  :STRING => 14,
  :VARIABLE_NAME => 15,
  :INTEGER => 16,
  "form" => 17,
  "end" => 18,
  ":" => 19,
  "boolean" => 20,
  "integer" => 21,
  "string" => 22,
  "if" => 23,
  "(" => 24,
  ")" => 25,
  "else" => 26,
  "true" => 27,
  "false" => 28 }

racc_nt_base = 29

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"==\"",
  "\"!=\"",
  "\"<=\"",
  "\"<\"",
  "\">=\"",
  "\">\"",
  "\"&&\"",
  "\"||\"",
  "STRING",
  "VARIABLE_NAME",
  "INTEGER",
  "\"form\"",
  "\"end\"",
  "\":\"",
  "\"boolean\"",
  "\"integer\"",
  "\"string\"",
  "\"if\"",
  "\"(\"",
  "\")\"",
  "\"else\"",
  "\"true\"",
  "\"false\"",
  "$start",
  "form",
  "variable_name",
  "statements",
  "statement",
  "question",
  "conditional",
  "description",
  "type",
  "if",
  "if_else",
  "expression",
  "constant",
  "integer",
  "string",
  "boolean" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
 result = Form.new(val[1], val[2]) 
    result
end

def _reduce_2(val, _values, result)
 result = val[0].push(val[1]) 
    result
end

def _reduce_3(val, _values, result)
 result = [ val[0] ] 
    result
end

# reduce 4 omitted

# reduce 5 omitted

def _reduce_6(val, _values, result)
 result = Question.new(val[0], val[1], val[3]) 
    result
end

def _reduce_7(val, _values, result)
 result = val[0][1..-2] 
    result
end

# reduce 8 omitted

def _reduce_9(val, _values, result)
 result = BooleanType.new 
    result
end

def _reduce_10(val, _values, result)
 result = IntegerType.new 
    result
end

def _reduce_11(val, _values, result)
 result = StringType.new 
    result
end

# reduce 12 omitted

# reduce 13 omitted

def _reduce_14(val, _values, result)
 result = If.new(val[2], val[4]) 
    result
end

def _reduce_15(val, _values, result)
 result = IfElse.new(val[2], val[4], val[6]) 
    result
end

def _reduce_16(val, _values, result)
 result = Equal.new(val[0], val[2]) 
    result
end

def _reduce_17(val, _values, result)
 result = LessThanOrEqualTo.new(val[0], val[2]) 
    result
end

def _reduce_18(val, _values, result)
 result = LessThan.new(val[0], val[2]) 
    result
end

def _reduce_19(val, _values, result)
 result = GreaterThanOrEqualTo.new(val[0], val[2]) 
    result
end

def _reduce_20(val, _values, result)
 result = GreaterThan.new(val[0], val[2]) 
    result
end

def _reduce_21(val, _values, result)
 result = Inequal.new(val[0], val[2]) 
    result
end

def _reduce_22(val, _values, result)
 result = And.new(val[0], val[2]) 
    result
end

def _reduce_23(val, _values, result)
 result = Or.new(val[0], val[2]) 
    result
end

def _reduce_24(val, _values, result)
 result = Multiplication.new(val[0], val[2]) 
    result
end

def _reduce_25(val, _values, result)
 result = Division.new(val[0], val[2]) 
    result
end

def _reduce_26(val, _values, result)
 result = Plus.new(val[0], val[2]) 
    result
end

def _reduce_27(val, _values, result)
 result = Minus.new(val[0], val[2]) 
    result
end

# reduce 28 omitted

# reduce 29 omitted

def _reduce_30(val, _values, result)
 result = Variable.new(val[0]) 
    result
end

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

def _reduce_34(val, _values, result)
 result = IntegerLiteral.new(val[0].to_i) 
    result
end

def _reduce_35(val, _values, result)
 result = StringLiteral.new(val[0][1..-2]) 
    result
end

def _reduce_36(val, _values, result)
 result = BooleanLiteral.new(true) 
    result
end

def _reduce_37(val, _values, result)
 result = BooleanLiteral.new(false) 
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module QL
